### ISSUE TITLE
Plotting packages in Julia

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/YaoPlots.jl#1]
- [ ] [Luxor.jl](https://github.com/JuliaGraphics/Luxor.jl)
- [ ] [PyPlot.jl](https://github.com/JuliaPy/PyPlot.jl)
- [ ] [PlotlyJS.jl](https://github.com/sglyon/PlotlyJS.jl)
- [ ] [GR.jl](https://github.com/jheinen/GR.jl)
- [ ] [UnicodePlots.jl](https://github.com/Evizero/UnicodePlots.jl)
- [ ] [Gadfly.jl](https://github.com/GiovineItalia/Gadfly.jl)
- [ ] [VegaLite.jl](https://github.com/fredo-dedup/VegaLite.jl)
- [ ] [Compoise.jl](https://github.com/GiovineItalia/Compose.jl) (very light weight)

cc: @taineleau

**Comment by GiggleLiu** [comment]
I benchmarked for the first plot issue, hope is can help you making decisions.

https://github.com/GiggleLiu/firstplotbench/blob/master/plottime/README.md

**Comment by GiggleLiu** [comment]
We choose Compose! Close
