### ISSUE TITLE
Rotation about 2 qubit axis shows gate on multiple qubits

### ISSUE THREAD

**Issue by vipasu** [QuantumBFS/YaoPlots.jl#28]
Minimal example that can be copy-pasted into Pluto
```julia
begin
	using Yao, YaoPlots, YaoExtensions
	N = 4
	d = 1
	ising(nbit, i, j) = rot(kron(nbit, i=>X, j=>X), 0.0)
	circuit = dispatch!(variational_circuit(N, d, pair_ring(N), entangler=ising), :zero)

	circuit |> vizcircuit(scale=0.7)
end
```

2 things that would be useful to fix/have
- Each of the entangling gates shows up as 4 blocks but it should show up only as 2
- A labeling string, like the single qubit rotations

**Comment by GiggleLiu** [comment]
Thanks for the issue!
The second point,

> A labeling string, like the single qubit rotations

We don't have a scheme in mind about how to put labels in these squares yet. We just left them empty as a warning sign that they are not defined. Do you have any good suggestion?

**Comment by vipasu** [comment]
Haha, I was actually just thinking about this representation difficulty the other day. To my knowledge this is not standardized? But perhaps that means it is a good time to establish one.

A rough idea could be to write the label along the "wire" that connects the two blocks. If that is too cluttered, perhaps one could thicken the line to a rectangle between the two blocks (resembling something like a barbell) and write the label in the middle. In the case of multiple qubit gates, it could be a rectangular label that spans the farthest two qubits with the width of the rectangle expanded around the other qubits involved. 

Sorry if this text description is too difficult to parse. I can come up with a sketch if it sounds interesting.
