### ISSUE TITLE
Error displaying Grover's circuit

### ISSUE THREAD

**Issue by johnhearn** [QuantumBFS/YaoPlots.jl#33]
The following part of the [Grover tutorial](https://tutorials.yaoquantum.org/dev/generated/quick-start/3.grover-search/) results in an error.

```
N = 4
reflect0 = control(N, -collect(1:N-1), N=>-Z)
vizcircuit(reflect0)
```

`block type Scale{Val{-1},1,ZGate} does not support visualization.`

In this case it could be resolved by adding a minus sign to the gate name. Not sure what the general solution would be.

**Comment by GiggleLiu** [comment]
thanks for the issue, how about compiling it to

control angle * control z

It is much easier to implement.

**Comment by GiggleLiu** [comment]
What about rendering the above gate like this?
![reflect](https://user-images.githubusercontent.com/6257240/97517695-11c1ad80-196c-11eb-9671-5d0fecb3edcc.png)

Note: If the scale is not unitary, it will still throw an error.

Another example:
```julia
julia> control(N, -collect(1:4-1), 4=>-chain(Z, X, Y)) |> vizcircuit
```
![image](https://user-images.githubusercontent.com/6257240/97517762-3584f380-196c-11eb-99c5-fe4136f65ec3.png)

**Comment by johnhearn** [comment]
That's a clever solution and certainly makes sense.

The only downside I can see is that it's not a direct representation of the original code. For didactic purposes it might be a bit confusing but the most important thing is that it renders as a valid circuit.

Just for completeness maybe something like this would be more representative but probably not easy to implement (sorry for the ugly cut&paste):

![scale_gate](https://user-images.githubusercontent.com/3379944/97537287-db614e00-19be-11eb-88d6-cc1ebc2a50d1.png)

**Comment by GiggleLiu** [comment]
I also considered your version. But if you try the new example I showed, you will find it hard to fit in this diagram.

QBIR plot can not be a direct representation of the original code. The best practice is avoiding using non-standard gates in the code.

**Comment by johnhearn** [comment]
Makes total sense. Thanks.
