### ISSUE TITLE
Support for Daggered Block

### ISSUE THREAD

**Issue by VarLad** [QuantumBFS/YaoPlots.jl#36]
YaoPlots doesn't support Daggered block yet. Any support is appreciated！

**Comment by VarLad** [comment]
Also, while you guys are at it, would you mind making a "better" representation of the Measure block?
Something like this maybe?😅 ![IMG-20201215-WA0006.jpg](https://user-images.githubusercontent.com/51269425/102253562-7a211a00-3f2d-11eb-923c-4016c50556db.jpg)

**Comment by GiggleLiu** [comment]
Yeah, measurement gate is quite important.
Do you think the following version good enough?

![image](https://user-images.githubusercontent.com/6257240/102295007-7df67180-3f18-11eb-8adb-df39f59ad3c6.png)

**Comment by GiggleLiu** [comment]
About the daggered gate, it is very hard. Compose does not support latex strings. I can draw something like 

![image](https://user-images.githubusercontent.com/6257240/102295153-cd3ca200-3f18-11eb-8c0b-4c8cb6bda3ba.png)

However, superscipt is hard.

**Comment by VarLad** [comment]
> Yeah, measurement gate is quite important.
> Do you think the following version good enough?
> 
> ![image](https://user-images.githubusercontent.com/6257240/102295007-7df67180-3f18-11eb-8adb-df39f59ad3c6.png)

Perfect！

**Comment by VarLad** [comment]
> About the daggered gate, it is very hard. Compose does not support latex strings. I can draw something like
> 
> ![image](https://user-images.githubusercontent.com/6257240/102295153-cd3ca200-3f18-11eb-8c0b-4c8cb6bda3ba.png)
> 
> However, superscipt is hard.

That would do！

**Comment by GiggleLiu** [comment]
@clad26 
I am wondering what is the using case of you daggered block. Most gates in Yao does not need the Daggered type to represent the conjugate transpose of a gate.

e.g. 
```julia
julia> Rx(0.5)'
rot(X, -0.5)
```

Implementing a general dagger is very hard, because dagger can also be applied on a big chunk of circuit.

**Comment by VarLad** [comment]
Uncomputation！
Encountered it for the first time in IBM Quantum Challenge！
It was used rigorously during the challenge！

**Comment by VarLad** [comment]
> @clad26 
> Implementing a general dagger is very hard, because dagger can also be applied on a big chunk of circuit.

I figured so... and mentioned in the slack that it would be tough to implement！😅

**Comment by VarLad** [comment]
A better step would be, to represent the Daggered circuit as QBIR notation in Yao itself, that would be much more efficient than calling it "Daggered Type".
Then we won't need a separate plot for Daggered block.
On that note, should I open an issue on Yao？

**Comment by GiggleLiu** [comment]
Emm, but we have Daggered type in Yao.

```julia
julia> using Yao, YaoExtensions

julia> FSimGate(0.6, 0.3)' |> typeof
Daggered{FSimGate{Float64},2}

julia> c = chain(4, put(2=>X), put((2,4)=>FSimGate(0.6, 0.3)))
nqubits: 4
chain
├─ put on (2)
│  └─ X
└─ put on (2, 4)
   └─ FSimGate{Float64}

julia> c'
nqubits: 4
chain
├─ put on (2, 4)
│  └─  [†]FSimGate{Float64}
└─ put on (2)
   └─ X


julia> Daggered(c)
nqubits: 4
 [†]chain
   ├─ put on (2)
   │  └─ X
   └─ put on (2, 4)
      └─ FSimGate{Float64}
```

**Comment by GiggleLiu** [comment]
The point is, in most cases. Calling the adjoint will convert the daggered gate to a known gate automatically. So, normally one should not notice the dagger issue. Maybe I should add a patch to support **constant or matrix single qubit gates** (ConstantGate and GeneralMatrixBlock) to support user defined gates better, does it sound good?

**Comment by VarLad** [comment]
Wait a second....
Daggered(circuit) is equivalent to circuit'
？

**Comment by GiggleLiu** [comment]
Yeah, but how to represent the dagger of an FSim gate without using the Daggered?

**Comment by VarLad** [comment]
> Wait a second....
Daggered(circuit) is equivalent to circuit'
？

If this is the case, then is it possible to, for ```
plot(Daggered(circuit))
```, we can just ```
plot(Daggered(circuit)'') ``` ？

**Comment by VarLad** [comment]
> > Wait a second....
> Daggered(circuit) is equivalent to circuit'
> ？
> 
> If this is the case, then is it possible to, for plot(Daggered(circuit)), we can just plot(Daggered(circuit)'') ？

This would be the best solution to daggered plot, if possible！🙁

**Comment by GiggleLiu** [comment]
> Wait a second....
> Daggered(circuit) is equivalent to circuit'
> ？

Nope, See the dagger sign before the circuit. In the terminal, the sign is in yellow, so is much easier to read.

> If this is the case, is it possible to just obtain the circuit without the dagger, then plot its adjoint？

But, we need to represent the dagger of FSim gate, even though we did not define the adjoint for it.

**Comment by VarLad** [comment]
Can we "convert" the Daggered Type into a normal Chain Block？

**Comment by GiggleLiu** [comment]
> Can we "convert" the Daggered Type into a normal Chain Block？

```julia
julia> c'
nqubits: 4
chain
├─ put on (2, 4)
│  └─  [†]FSimGate{Float64}
└─ put on (2)
   └─ X
```

Yeah, we have already done this. But for primitive types, it is not possible.

**Comment by VarLad** [comment]
> Nope, See the dagger sign before the circuit. In the terminal, the sign is in yellow, so is much easier to read.

```
a = chain(2, put(1=>X), put(1=>H))
```
Yeah but 
```
Matrix(Daggered(a)) == Matrix(a')
```
gives true...

So isn't the operation both Daggered(a) and a' perform, on a pair of quibits, essentially the same？🙁

**Comment by GiggleLiu** [comment]
> > Nope, See the dagger sign before the circuit. In the terminal, the sign is in yellow, so is much easier to read.
> 
> ```
> a = chain(2, put(1=>X), put(1=>H))
> ```
> 
> Yeah but
> 
> ```
> Matrix(Daggered(a')) == Matrix(a)
> ```
> 
> gives true...

Ah, i see. I eye was blind for a while.

**Comment by GiggleLiu** [comment]
> So isn't the operation both Daggered(a) and a' perform, on a pair of quibits, essentially the same？

Daggered is the constructor of the Daggered type. But `'` calls the `Base.adjoint` function.
It is consistent with the Ajoint in Julia base.

```julia
julia> using LinearAlgebra

julia> h = Hermitian(randn(2, 2))
2×2 Hermitian{Float64,Array{Float64,2}}:
  0.174737   -0.0861846
 -0.0861846  -2.39919

julia> h'
2×2 Hermitian{Float64,Array{Float64,2}}:
  0.174737   -0.0861846
 -0.0861846  -2.39919

julia> Adjoint(h)
2×2 Adjoint{Float64,Hermitian{Float64,Array{Float64,2}}}:
  0.174737   -0.0861846
 -0.0861846  -2.39919
```

Normally, users do not need to use `Daggered` or `Adjoint`.

**Comment by VarLad** [comment]
> So isn't the operation both Daggered(a) and a' perform, on a pair of quibits, essentially the same？🙁

So, if this works, plotting Daggered(circuit) should be equivalent to plotting circuit'　(as both are performing the same operation on qubits)

**Comment by GiggleLiu** [comment]
> > So isn't the operation both Daggered(a) and a' perform, on a pair of quibits, essentially the same？slightly_frowning_face
> 
> So, if this works, plotting Daggered(circuit) should be equivalent to plotting circuit'　(as both are performing the same operation on qubits)

It is not recommented to use the Daggered type directly, when it appears, it usually means the `'` can not propagate anymore. So it does not make sense to do another transformation, it only gives you the Stackoverflow Error.

**Comment by VarLad** [comment]
So I can just use ' when I want the dagger of a circuit, and not the Daggered type？
That would get me a normal plot too

**Comment by GiggleLiu** [comment]
> So I can just use ' when I want the dagger of a circuit, and not the Daggered type？
> That would get me a normal plot too

Yes!

**Comment by VarLad** [comment]
This solves my problem！Thanks！
I was wondering if you could make something using which, I can plot a circuit, as a big rectangular box, in Yao？

**Comment by GiggleLiu** [comment]
> This solves my problem！Thanks！
> I was wondering if you could make something using which, I can plot a circuit, as a big rectangular box, in Yao？

That might be hard, because the wires might be non-continuous. I do not know how to distinguish connected and not connected wires.

**Comment by VarLad** [comment]
Something like
```
circuit = chain(3,  put(1=>X), name="circuit")
a = chain(4, put(1:3=>circuit), put(2=>H), put(4=>X))
plot_oracle(a)
```
![_20201217_012514.JPG](https://user-images.githubusercontent.com/51269425/102399583-d0ae5700-4006-11eb-9af7-61d37d6fde4f.JPG)
？

**Comment by VarLad** [comment]
@GiggleLiu If its possible, that would be a great help in designing and visualizing circuits！😅

**Comment by GiggleLiu** [comment]
If you do not mind changing the circuit a bit, I can make a helper block to wrap the sub-block with continuous locations.

**Comment by VarLad** [comment]
For example？

**Comment by GiggleLiu** [comment]
See https://github.com/QuantumBFS/YaoPlots.jl/pull/40
