### ISSUE TITLE
Error with vizcircuit argument "filename"

### ISSUE THREAD

**Issue by Shinibali** [QuantumBFS/YaoPlots.jl#57]
I have been trying to save a vizcircuit plot as a pdf file. I keep getting to following error:

ERROR: MethodError: no method matching vizcircuit(::ChainBlock{2}; filename="C:/Users/Documents/research/yao_practice/qft.pdf")
Closest candidates are:
  vizcircuit(::AbstractBlock; w_depth, w_line, scale, show_ending_bar, starting_texts, starting_offset, ending_texts, ending_offset, graphsize, gatestyles) at C:\Users\shini\.julia\packages\YaoPlots\fhJ3Z\src\vizcircuit.jl:260 got unsupported keyword argument "filename"
  vizcircuit(; kwargs...) at C:\Users\shini\.julia\packages\YaoPlots\fhJ3Z\src\vizcircuit.jl:290
Stacktrace:
 [1] kwerr(::NamedTuple{(:filename,), Tuple{String}}, ::Function, ::ChainBlock{2})
   @ Base .\error.jl:163
 [2] top-level scope
   @ Untitled-1:7

**Comment by GiggleLiu** [comment]
This is wield, can you please check your package version using
```julia
pkg> status
```

Just make sure you are using YaoPlots 0.8.
