### ISSUE TITLE
LabelBlock is not working correctly

### ISSUE THREAD

**Issue by hmunozb** [QuantumBFS/YaoPlots.jl#58]
LabelBlock currently does not work correctly. The most recent version with the correct behavior is 0.7.3

```julia
addlabel(H, "G")
```
Expected: `-[G]-`.  Actual: `-[H]-`. It looks like the cause is #55  [redefining draw! for LabelBlock](https://github.com/QuantumBFS/YaoPlots.jl/blob/67a79c239491fbfa7e498cb036e58ecf2994a776/src/vizcircuit.jl#L321-L327).

**Comment by GiggleLiu** [comment]
Yeah, just confirmed. Thanks for your bug report!
